package com.nomad.model;

public enum ManagerCommand {
    GET_SERVER_INFO, GET_MEMORY_INFO, GET_OBJECT_COUNT_INFO, CLEAN_CACHE, GET_CACHE_KEYS, PING, UPLOAD_PLUGIN, REGISTER_SERVER, REGISTER_CLIENT, CHECK_SESSIONS, REGISTER_MODEL, REGISTER_COMMAND, CHANGE_LISTENER_STATUS
}
