package com.nomad.message;


public enum OperationStatus {
    OK, EMPTY_ANSWER, ERROR, INVALID_SESSION, LOGICAL_ERROR, BLOCKED, TIMEOUT, TRANSPORT_ERROR, UNSUPPORTED_MODEL_NAME, INVALID_OPERATION_NAME, ACCESS_DENIED, MODEL_NOT_EXIST, RELATION_NOT_EXIST, UPDATE_MODEL_ERROR;

}
